version: '3.8'
services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    image: laravel-app
    container_name: 5csoport-app-container
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - 5csoport-network
  db:
    image: mysql:8.0.40
    container_name: 5csoport-db-container
    restart: unless-stopped
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: 5csoport_webaruhaz
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_PASSWORD: user
      MYSQL_USER: user
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - 5csoport-network
  nginx:
    image: nginx:alpine
    container_name: 5csoport-ngnix-container
    restart: unless-stopped
    ports:
      - 8000:80
    volumes:
      - ./:/var/www
      - ./docker-compose/nginx:/etc/nginx/conf.d/
    networks:
      - 5csoport-network
networks:
  5csoport-network:
    driver: bridge
volumes:
  dbdata:
    driver: local